config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :activity_types
  resources :acitivty_types
  resources :challenges

  get 'add_participant/:challenge_id', to: 'challenges_users#new', as: 'add_participant'
  post 'add_participant/:challenge_id', to: 'challenges_users#create', as: 'create_participant'

  devise_for :users
  mount Sidekiq::Web => "/sidekiq" # monitoring console
  root "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/activity_types_controller.rb
class ActivityTypesController < ApplicationController
  before_action :set_activity_type, only: [:show, :edit, :update, :destroy]

  # GET /activity_types
  def index
    @activity_types = ActivityType.all
  end

  # GET /activity_types/1
  def show
  end

  # GET /activity_types/new
  def new
    @activity_type = ActivityType.new
  end

  # GET /activity_types/1/edit
  def edit
  end

  # POST /activity_types
  def create
    @activity_type = ActivityType.new(activity_type_params)

    if @activity_type.save
      redirect_to @activity_type, notice: 'Activity type was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /activity_types/1
  def update
    if @activity_type.update(activity_type_params)
      redirect_to @activity_type, notice: 'Activity type was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /activity_types/1
  def destroy
    @activity_type.destroy
    redirect_to activity_types_url, notice: 'Activity type was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity_type
      @activity_type = ActivityType.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def activity_type_params
      new_params = params.require(:activity_type).permit(:name, :emoji, :measure, :time_conversion)
    end
end

app/helpers/activity_types_helper.rb
module ActivityTypesHelper
end

app/views/activity_types/_form.html.erb
<%= bootstrap_form_for(@activity_type) do |f| %>

  <%= f.alert_message "Please review the problems below:" %>

  <%= f.text_field :name %>
  <!-- <%= f.text_field :emoji %> -->
  <!-- <%= f.number_field :measure %> -->
  <%= f.select :measure, ActivityType.measures.keys.map { |w| [w.humanize, w] } %>
  <%= f.number_field :time_conversion, label: 'Number of steps per minute (N/A for steps measure)' %>

  <%= f.primary %>
  <%= link_to "Back", activity_types_path, class: "btn btn-link" %>

<% end %>

app/views/activity_types/edit.html.erb
<% provide(:title, "Editing activity_type") %>

<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/activity_types/index.html.erb
<% provide(:title, "Listing activity_types") %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <!-- <th>Emoji</th> -->
      <th>Measure</th>
      <th>Time conversion</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @activity_types.each do |activity_type| %>
      <tr>
        <td><%= activity_type.name %></td>
        <!-- <td><%= activity_type.emoji %></td> -->
        <td><%= activity_type.measure %></td>
        <td><%= activity_type.time_conversion %></td>
        <td>
          <div class="btn-group">
            <%= link_to activity_type, class: "btn btn-xs btn-default" do %>
              <%= fa_icon("eye", text: "Show") %>
            <% end %>
            <%= link_to edit_activity_type_path(activity_type), class: "btn btn-xs btn-default" do %>
              <%= fa_icon("pencil", text: "Edit") %>
            <% end %>
            <%= link_to activity_type, class: "btn btn-xs btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this activity_type?" } do %>
              <%= fa_icon("trash-o", text: "Destroy") %>
            <% end %>
          </div>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_activity_type_path, class: "btn btn-default" do %>
  <%= fa_icon("plus", text: "New Activity type") %>
<% end %>

app/views/activity_types/new.html.erb
<% provide(:title, "New activity_type") %>

<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/activity_types/show.html.erb
<% provide(:title) do %>
  Activity Type #<%= @activity_type.id %>
<% end %>

<table class="table table-bordered">
  <tbody>
    <tr>
      <th class="col-sm-2">Name</th>
      <td><%= @activity_type.name %></td>
    </tr>
    <!-- <tr>
      <th class="col-sm-2">Emoji</th>
      <td><%= @activity_type.emoji %></td>
    </tr> -->
    <tr>
      <th class="col-sm-2">Measure</th>
      <td><%= @activity_type.measure %></td>
    </tr>
    <tr>
      <th class="col-sm-2">Time conversion</th>
      <td><%= @activity_type.time_conversion %></td>
    </tr>
  </tbody>
</table>

<p>
  <%= link_to "Edit", edit_activity_type_path(@activity_type), class: "btn btn-primary" %>
  <%= link_to "Back", activity_types_path, class: "btn btn-link" %>
</p>