config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :activity_types
  resources :acitivty_types
  resources :challenges

  get 'add_participant/:challenge_id', to: 'challenges_users#new', as: 'add_participant'
  post 'add_participant/:challenge_id', to: 'challenges_users#create', as: 'create_participant'

  devise_for :users
  mount Sidekiq::Web => "/sidekiq" # monitoring console
  root "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :activities

  def points_for(user)
    tempObj = Struct.new(:date, :points)
    activities.where(user: user).map { |a| tempObj.new(a.date, a.points) }
  end

  def days
    (end_date - start_date) / 1.day
  end

  def points_by_day(user)
    points = points_for(user).group_by &:date
    by_day = points.map{ |date, p|
      [ date_to_day(date.to_date), p.reduce(0) { |sum, n| sum + n.points } ]
    }.sort_by { |x| x[0] } # sort by date

    # cum_sum
    sum = 0
    by_day.map{|date, x| [date, sum += x] }
  end

  def leaderboard
    users.map { |user|
      [ user, points_by_day(user)[-1] || 0 ]
    }.sort_by { |x| -x[1][-1]} # sort by points
  end

  private
  def date_to_day(date)
    (date.to_date - start_date.to_date).to_i
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]

  # GET /challenges
  def index
    @challenges = Challenge.all
  end

  # GET /challenges/1
  def show
    @leaderboard = @challenge.leaderboard
    @colors = 100.times.map{"#%06x" % (rand * 0x1000000)}
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges
  def create
    @challenge = Challenge.new(challenge_params)

    if @challenge.save
      redirect_to @challenge, notice: 'Challenge was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /challenges/1
  def update
    if @challenge.update(challenge_params)
      redirect_to @challenge, notice: 'Challenge was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /challenges/1
  def destroy
    @challenge.destroy
    redirect_to challenges_url, notice: 'Challenge was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def challenge_params
      params.require(:challenge).permit(:title, :start_date, :end_date)
    end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_challenge.html.erb
<div><%= link_to challenge.title, challenge %><div>

app/views/challenges/_form.html.erb
<%= bootstrap_form_for(@challenge) do |f| %>

  <%= f.alert_message "Please review the problems below:" %>

  <%= f.text_field :title %>
  <%= f.datetime_select :start_date %>
  <%= f.datetime_select :end_date %>

  <%= f.primary %>
<% end %>

app/views/challenges/edit.html.erb
<% provide(:title, "Editing challenge") %>

<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/challenges/index.html.erb
<% provide(:title, "Listing challenges") %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Start date</th>
      <th>End date</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @challenges.each do |challenge| %>
      <tr>
        <td><%= challenge.title %></td>
        <td><%= challenge.start_date %></td>
        <td><%= challenge.end_date %></td>
        <td>
          <div class="btn-group">
            <%= link_to challenge, class: "btn btn-xs btn-default" do %>
              <%= fa_icon("eye", text: "Show") %>
            <% end %>
            <%= link_to edit_challenge_path(challenge), class: "btn btn-xs btn-default" do %>
              <%= fa_icon("pencil", text: "Edit") %>
            <% end %>
            <%= link_to challenge, class: "btn btn-xs btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this challenge?" } do %>
              <%= fa_icon("trash-o", text: "Destroy") %>
            <% end %>
          </div>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_challenge_path, class: "btn btn-default" do %>
  <%= fa_icon("plus", text: "New Challenge") %>
<% end %>

app/views/challenges/new.html.erb
<% provide(:title, "New challenge") %>

<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/challenges/show.html.erb
<% provide(:title) do
  "#{@challenge.title} (#{@challenge.start_date.strftime('%B %e, %Y')} - #{@challenge.end_date.strftime('%B %e, %Y')})"
end %>


<%
data = {
  labels: (0..@challenge.days).to_a,
  datasets: @challenge.users.to_a.each_with_index.map { |user, i|
    {
        label: user.username,
        backgroundColor: "rgba(220,220,220,0.2)",
        borderColor: @colors[i],
        data: @challenge.points_by_day(user).map { |date, value| { x: date, y: value } }
    }
  }
}
%>



<div class="row">
  <div class="col-sm-6">
    <div class="chart">
      <%= line_chart data, options: { responsive: true, maintainAspectRatio: false} %>
    </div>
  </div>
  <div class="col-sm-6">

    <div class="center">
      <div class="top3">
        <% if @leaderboard.count > 1 %>
        <div class="two item">
          <div class="pos">
            2
          </div>
          <div class="pic" style="background-image: url(&#39;https://randomuser.me/api/portraits/men/44.jpg&#39;)"></div>
          <div class="name">
            <%= @leaderboard[1][0].username %>
          </div>
          <div class="score">
            <%= @leaderboard[1][1][1] %>
          </div>
        </div>
        <% end %>
        <% if @leaderboard.count > 0 %>
        <div class="one item">
          <div class="pos">
            1
          </div>
          <div class="pic" style="background-image: url(&#39;https://randomuser.me/api/portraits/men/31.jpg&#39;)"></div>
          <div class="name">
            <%= @leaderboard[0][0].username %>
          </div>
          <div class="score">
            <%= @leaderboard[0][1][1] %>
          </div>
        </div>
        <% end %>
        <% if @leaderboard.count > 2 %>
        <div class="three item">
          <div class="pos">
            3
          </div>
          <div class="pic" style="background-image: url(&#39;https://randomuser.me/api/portraits/women/91.jpg&#39;)"></div>
          <div class="name">
            <%= @leaderboard[2][0].username %>
          </div>
          <div class="score">
            <%= @leaderboard[2][1][1] %>
          </div>
        </div>
        <% end %>
      </div>
      <% if @leaderboard.count > 3 %>
      <div class="list">
          <% @leaderboard[3..@leaderboard.length].each_with_index do |position, i| %>
            <div class="item">
              <div class="pos">
                <%= i+4 %>
              </div>
              <div class="pic" style="background-image: url(&#39;https://randomuser.me/api/portraits/women/29.jpg&#39;)"></div>
              <div class="name">
                <%= position[0].username %>
              </div>
              <div class="score">
                <%= position[1][1] %>
              </div>
            </div>
            <% end %>
      </div>
      <% end %>
    </div>


  </div>
</div>

<%= link_to "Log activity", new_activity_path(challenge_id: @challenge), class: 'btn btn-primary' %>
<%= link_to "Add Participant", add_participant_path(@challenge.id), class: 'btn btn-default' %>

<div class="row">
  <div class="col-lg-6 col-md-8 col-sm-12 col-xs-12">
    <h2>Activity</h2>
    <%= render @challenge.activities.order(:date) %>
  </div>
</div>


<!-- <p>
  <%= link_to "Edit", edit_challenge_path(@challenge), class: "btn btn-primary" %>
  <%= link_to "Back", challenges_path, class: "btn btn-link" %>
</p> -->