config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :activity_types
  resources :acitivty_types
  resources :challenges

  get 'add_participant/:challenge_id', to: 'challenges_users#new', as: 'add_participant'
  post 'add_participant/:challenge_id', to: 'challenges_users#create', as: 'create_participant'

  devise_for :users
  mount Sidekiq::Web => "/sidekiq" # monitoring console
  root "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/acitivty_types_controller.rb
class AcitivtyTypesController < ApplicationController
  before_action :set_acitivty_type, only: [:show, :edit, :update, :destroy]

  # GET /acitivty_types
  def index
    @acitivty_types = AcitivtyType.all
  end

  # GET /acitivty_types/1
  def show
  end

  # GET /acitivty_types/new
  def new
    @acitivty_type = AcitivtyType.new
  end

  # GET /acitivty_types/1/edit
  def edit
  end

  # POST /acitivty_types
  def create
    @acitivty_type = AcitivtyType.new(acitivty_type_params)

    if @acitivty_type.save
      redirect_to @acitivty_type, notice: 'Acitivty type was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /acitivty_types/1
  def update
    if @acitivty_type.update(acitivty_type_params)
      redirect_to @acitivty_type, notice: 'Acitivty type was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /acitivty_types/1
  def destroy
    @acitivty_type.destroy
    redirect_to acitivty_types_url, notice: 'Acitivty type was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acitivty_type
      @acitivty_type = AcitivtyType.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def acitivty_type_params
      params.require(:acitivty_type).permit(:name, :emoji, :measure, :time_conversion)
    end
end

app/helpers/acitivty_types_helper.rb
module AcitivtyTypesHelper
end

app/views/acitivty_types/_form.html.erb
<%= bootstrap_form_for(@acitivty_type) do |f| %>

  <%= f.alert_message "Please review the problems below:" %>

  <%= f.text_field :name %>
  <%= f.text_field :emoji %>
  <%= f.number_field :measure %>
  <%= f.number_field :time_conversion %>

  <%= f.primary %>
  <%= link_to "Back", acitivty_types_path, class: "btn btn-link" %>

<% end %>

app/views/acitivty_types/edit.html.erb
<% provide(:title, "Editing acitivty_type") %>

<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/acitivty_types/index.html.erb
<% provide(:title, "Listing acitivty_types") %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Emoji</th>
      <th>Measure</th>
      <th>Time conversion</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @acitivty_types.each do |acitivty_type| %>
      <tr>
        <td><%= acitivty_type.name %></td>
        <td><%= acitivty_type.emoji %></td>
        <td><%= acitivty_type.measure %></td>
        <td><%= acitivty_type.time_conversion %></td>
        <td>
          <div class="btn-group">
            <%= link_to acitivty_type, class: "btn btn-xs btn-default" do %>
              <%= fa_icon("eye", text: "Show") %>
            <% end %>
            <%= link_to edit_acitivty_type_path(acitivty_type), class: "btn btn-xs btn-default" do %>
              <%= fa_icon("pencil", text: "Edit") %>
            <% end %>
            <%= link_to acitivty_type, class: "btn btn-xs btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this acitivty_type?" } do %>
              <%= fa_icon("trash-o", text: "Destroy") %>
            <% end %>
          </div>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_acitivty_type_path, class: "btn btn-default" do %>
  <%= fa_icon("plus", text: "New Acitivty type") %>
<% end %>

app/views/acitivty_types/new.html.erb
<% provide(:title, "New acitivty_type") %>

<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/acitivty_types/show.html.erb
<% provide(:title) do %>
  Acitivty Type #<%= @acitivty_type.id %>
<% end %>

<table class="table table-bordered">
  <tbody>
    <tr>
      <th class="col-sm-2">Name</th>
      <td><%= @acitivty_type.name %></td>
    </tr>
    <!-- <tr>
      <th class="col-sm-2">Emoji</th>
      <td><%= @acitivty_type.emoji %></td>
    </tr> -->
    <tr>
      <th class="col-sm-2">Measure</th>
      <td><%= @acitivty_type.measure %></td>
    </tr>
    <tr>
      <th class="col-sm-2">Time conversion</th>
      <td><%= @acitivty_type.time_conversion %></td>
    </tr>
  </tbody>
</table>

<p>
  <%= link_to "Edit", edit_acitivty_type_path(@acitivty_type), class: "btn btn-primary" %>
  <%= link_to "Back", acitivty_types_path, class: "btn btn-link" %>
</p>