config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :activity_types
  resources :acitivty_types
  resources :challenges

  get 'add_participant/:challenge_id', to: 'challenges_users#new', as: 'add_participant'
  post 'add_participant/:challenge_id', to: 'challenges_users#create', as: 'create_participant'

  devise_for :users
  mount Sidekiq::Web => "/sidekiq" # monitoring console
  root "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :activity_type
  belongs_to :challenge
  belongs_to :user

  def points
    if activity_type.time?
      activity_type.time_conversion * amount
    else
      amount
    end
  end

end

app/models/activity_type.rb
class ActivityType < ApplicationRecord
  enum measure: [ :steps, :time ]

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new(user: current_user, challenge_id: params[:challenge_id])
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  def create
    @activity = Activity.new(activity_params)

    if @activity.save
      # redirect_to @activity, notice: 'Activity was successfully created.'
      redirect_to @activity.challenge, notice: 'Activity was successfully logged.'
    else
      render :new
    end
  end

  # PATCH/PUT /activities/1
  def update
    if @activity.update(activity_params)
      redirect_to @activity, notice: 'Activity was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /activities/1
  def destroy
    @activity.destroy
    redirect_to activities_url, notice: 'Activity was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def activity_params
      params.require(:activity).permit(:activity_type_id, :challenge_id, :amount, :user_id, :date)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activity.html.erb
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <div class="pull-left">
      <h3 class="panel-title"><%= activity.user.username %></h3>
      <small><%= activity.date %></small>
    </div>
    <div class="pull-right">
      <p class="panel-title text-right"><%= activity.points %></p>
    </div>
  </div>
  <div class="panel-body">
    <% if activity.activity_type.time? %>
      Time: <%= activity.amount %>
    <% else %>
      Steps: <%= activity.amount %>
    <% end %><br>
    Sport: <%= activity.activity_type.name %><br>
  </div>
</div>

<!-- <div><%= activity.user.username %><div>
  <div><%= activity.activity_type.name %><div>
<div><%= activity.points %><div> -->

app/views/activities/_form.html.erb
<%= bootstrap_form_for(@activity) do |f| %>
  <%= f.alert_message "Please review the problems below:" %>
  <%= f.select(:challenge_id, Challenge.all.collect { |v| [ v.title, v.id ] }) %>
  <%= f.select(:user_id, User.all.collect { |v| [ v.username, v.id ] }) %>

  <%= f.select(:activity_type_id, ActivityType.all.collect { |v| [ v.name, v.id ] }) %>
  <%= f.number_field :amount, label: 'Time (minutes)' %>
  <%= f.date_select :date %>

  <%= f.primary %>
<% end %>

app/views/activities/edit.html.erb
<% provide(:title, "Editing activity") %>

<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/activities/index.html.erb
<% provide(:title, "Listing activities") %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Activity type</th>
      <th>Challenge</th>
      <th>Amount</th>
      <th>User</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.activity_type %></td>
        <td><%= activity.challenge %></td>
        <td><%= activity.amount %></td>
        <td><%= activity.user %></td>
        <td>
          <div class="btn-group">
            <%= link_to activity, class: "btn btn-xs btn-default" do %>
              <%= fa_icon("eye", text: "Show") %>
            <% end %>
            <%= link_to edit_activity_path(activity), class: "btn btn-xs btn-default" do %>
              <%= fa_icon("pencil", text: "Edit") %>
            <% end %>
            <%= link_to activity, class: "btn btn-xs btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this activity?" } do %>
              <%= fa_icon("trash-o", text: "Destroy") %>
            <% end %>
          </div>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_activity_path, class: "btn btn-default" do %>
  <%= fa_icon("plus", text: "New Activity") %>
<% end %>

app/views/activities/new.html.erb
<% provide(:title, "New activity") %>

<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/activities/show.html.erb
<% provide(:title) do %>
  Activity #<%= @activity.id %>
<% end %>

<table class="table table-bordered">
  <tbody>
    <tr>
      <th class="col-sm-2">Activity type</th>
      <td><%= @activity.activity_type %></td>
    </tr>
    <tr>
      <th class="col-sm-2">Challenge</th>
      <td><%= @activity.challenge %></td>
    </tr>
    <tr>
      <th class="col-sm-2">Amount</th>
      <td><%= @activity.amount %></td>
    </tr>
    <tr>
      <th class="col-sm-2">User</th>
      <td><%= @activity.user %></td>
    </tr>
  </tbody>
</table>

<p>
  <%= link_to "Edit", edit_activity_path(@activity), class: "btn btn-primary" %>
  <%= link_to "Back", activities_path, class: "btn btn-link" %>
</p>